name: Build and deploy main

on:
  push:
    branches: [master]

jobs:
  build:
    name: Build and deploy main
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2.1.5

      - name: Cache node modules
        uses: actions/cache@v2
        with:
          path: ~/node_modules
          key: cache-${{ hashFiles('**/package-lock.json') }}

      # pass --base for application to work under GitHub pages
      - name: Install and build
        run: |
          npm install
          npm run build -- --base=/${{ github.event.repository.name }}/

      - name: Publish deployed code 
        uses: actions/upload-artifact@v2
        with:
          name: published
          path: dist
